// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: user_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	//verify Code
	GetVerifyCode(ctx context.Context, in *RequestVerifyCode, opts ...grpc.CallOption) (*ResponseVerifyCode, error)
	//User register
	UserRegister(ctx context.Context, in *RequestUserList, opts ...grpc.CallOption) (UserService_UserRegisterClient, error)
	UserRegisterServerStream(ctx context.Context, in *RequestUserList, opts ...grpc.CallOption) (UserService_UserRegisterServerStreamClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetVerifyCode(ctx context.Context, in *RequestVerifyCode, opts ...grpc.CallOption) (*ResponseVerifyCode, error) {
	out := new(ResponseVerifyCode)
	err := c.cc.Invoke(ctx, "/pb.UserService/GetVerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserRegister(ctx context.Context, in *RequestUserList, opts ...grpc.CallOption) (UserService_UserRegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/pb.UserService/UserRegister", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceUserRegisterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_UserRegisterClient interface {
	Recv() (*ResponseUserList, error)
	grpc.ClientStream
}

type userServiceUserRegisterClient struct {
	grpc.ClientStream
}

func (x *userServiceUserRegisterClient) Recv() (*ResponseUserList, error) {
	m := new(ResponseUserList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) UserRegisterServerStream(ctx context.Context, in *RequestUserList, opts ...grpc.CallOption) (UserService_UserRegisterServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], "/pb.UserService/UserRegisterServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceUserRegisterServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_UserRegisterServerStreamClient interface {
	Recv() (*ResponseUserList, error)
	grpc.ClientStream
}

type userServiceUserRegisterServerStreamClient struct {
	grpc.ClientStream
}

func (x *userServiceUserRegisterServerStreamClient) Recv() (*ResponseUserList, error) {
	m := new(ResponseUserList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	//verify Code
	GetVerifyCode(context.Context, *RequestVerifyCode) (*ResponseVerifyCode, error)
	//User register
	UserRegister(*RequestUserList, UserService_UserRegisterServer) error
	UserRegisterServerStream(*RequestUserList, UserService_UserRegisterServerStreamServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetVerifyCode(context.Context, *RequestVerifyCode) (*ResponseVerifyCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifyCode not implemented")
}
func (UnimplementedUserServiceServer) UserRegister(*RequestUserList, UserService_UserRegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (UnimplementedUserServiceServer) UserRegisterServerStream(*RequestUserList, UserService_UserRegisterServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UserRegisterServerStream not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVerifyCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetVerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetVerifyCode(ctx, req.(*RequestVerifyCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserRegister_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestUserList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).UserRegister(m, &userServiceUserRegisterServer{stream})
}

type UserService_UserRegisterServer interface {
	Send(*ResponseUserList) error
	grpc.ServerStream
}

type userServiceUserRegisterServer struct {
	grpc.ServerStream
}

func (x *userServiceUserRegisterServer) Send(m *ResponseUserList) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_UserRegisterServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestUserList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).UserRegisterServerStream(m, &userServiceUserRegisterServerStreamServer{stream})
}

type UserService_UserRegisterServerStreamServer interface {
	Send(*ResponseUserList) error
	grpc.ServerStream
}

type userServiceUserRegisterServerStreamServer struct {
	grpc.ServerStream
}

func (x *userServiceUserRegisterServerStreamServer) Send(m *ResponseUserList) error {
	return x.ServerStream.SendMsg(m)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerifyCode",
			Handler:    _UserService_GetVerifyCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UserRegister",
			Handler:       _UserService_UserRegister_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UserRegisterServerStream",
			Handler:       _UserService_UserRegisterServerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user_service.proto",
}
